apiVersion: batch/v1
kind: Job
metadata:
  name: e2e
  labels:
    app: e2e
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: e2e
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: e2e-results-pvc
          persistentVolumeClaim:
            claimName: e2e-results-pvc
      containers:
        - name: e2e
          image: e2e-image:latest
          volumeMounts:
            - mountPath: /e2e/cypress/report
              name: e2e-results
          lifecycle:
            preStop:
              exec:
                command: ["curl", "-XPOST", "-u", "\":__USER_PAT__\"", "-H", "Content-type: application/json", "https://dev.azure.com/wdi23-dzaj/wdi23-dzaj/_apis/pipelines/{pipelineId}/runs?api-version=7.0"]
      restartPolicy: Never
  backoffLimit: 0