apiVersion: batch/v1
kind: Job
metadata:
  name: e2e
  labels:
    app: e2e
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: e2e
    spec:
      volumes:
        - name: e2e-results-pvc
          persistentVolumeClaim:
            claimName: e2e-results-pvc
      containers:
        - name: e2e
          imagePullPolicy: Always
          image: wdi23acr.azurecr.io/wdi23-e2e:latest
          volumeMounts:
            - mountPath: /mnt/e2e/cypress/report
              name: e2e-results-pvc
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "curl", "-XPOST", "-u", "\":wzzd5snp76qlxfd3sgfqg7ealqeqfuvxyrf5vapqpnqhx5ncrnfq\"", "-H", "Content-type: application/json", "-d", "{\"runParameters\": \"\"}", "https://dev.azure.com/dejvis/wdi23/_apis/pipelines/5/runs?api-version=7.0"]
      restartPolicy: Never
  backoffLimit: 0