apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    run: backend
spec:
  ports:
    - port: 4700
      targetPort: 4700
      protocol: TCP
  selector:
    app: backend
  type: LoadBalancer
  externalTrafficPolicy: Local