trigger: none

stages:
  - stage: Build_Docker_Image
    jobs:
      - job: Docker_Build_And_Deploy
        pool: SelfHosted
        steps:
          - checkout: self
            path: 'wdi23'

          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'wdi23-dzaj-rg'
              KeyVaultName: 'wdi23kv'
              SecretsFilter: '*'
              RunAsPreJob: true

          - task: CmdLine@2
            inputs:
              script: "sed -i 's/__USER_PAT__/$(WDI-PAT)/g' $(Agent.BuildDirectory)/wdi23/pipelines/deployment/e2e/job.yaml"

          - bash: |
              echo "##vso[task.setvariable variable=retrievepipelineid;]$(curl -s -u ":$(WDI-PAT)" 'https://dev.azure.com/dejvis/wdi23/_apis/pipelines?api-version=7.0' | jq -r '.value[] | select(.name=="retrieve-test-results") | .id')"

          - task: CmdLine@2
            inputs:
              script: "sed -i 's/__PIPELINE_ID__/$(retrievepipelineid)/g' $(Agent.BuildDirectory)/wdi23/pipelines/deployment/e2e/job.yaml"

          - task: Docker@2
            displayName: Build docker image
            inputs:
              containerRegistry: wdi23acr
              repository: wdi23-e2e
              command: 'buildAndPush'
              Dockerfile: '$(Agent.BuildDirectory)/wdi23/e2e/Dockerfile'
              tags: 'latest'

          - task: KubernetesManifest@0
            inputs:
              kubernetesServiceConnection: 'wdi23aks'
              action: 'deploy'
              namespace: 'e2e'
              manifests: '$(Agent.BuildDirectory)/wdi23/pipelines/deployment/e2e/job.yaml'