trigger: none

stages:
  - stage: Build_Docker_Image
    jobs:
      - job: Docker_Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            path: '$(Agent.BuildDirectory)/wdi23'

          - task: Docker@2
            displayName: Build docker image
            inputs:
              containerRegistry:
              repository: wdi23-backend
              command: 'buildAndPush'
              Dockerfile: '$(Agent.BuildDirectory)/wdi23/backend/Dockerfile'