trigger: none

stages:
  - stage: Build_Docker_Image
    jobs:
      - job: Docker_Build
        pool: Default
        steps:
          - checkout: self
            path: 'wdi23'

          - task: Docker@2
            displayName: Build docker image
            inputs:
              containerRegistry: wdi23acr
              repository: wdi23-e2e
              command: 'buildAndPush'
              Dockerfile: '$(Agent.BuildDirectory)/wdi23/e2e/Dockerfile'
              tags: 'latest'