trigger: none

stages:
  - stage: Build_Docker_Image
    jobs:
      - job: Docker_Build
        pool: SelfHosted
        steps:
          - checkout: self
            path: 'wdi23'

          - task: Docker@2
            displayName: Build docker image
            inputs:
              containerRegistry: wdi23acr
              repository: wdi23-backend
              command: 'buildAndPush'
              Dockerfile: '$(Agent.BuildDirectory)/wdi23/backend/Dockerfile'
              tags: 'latest'