trigger: none

stages:
  - stage: Build_Docker_Image
    jobs:
      - job: Docker_Build
        pool: SelfHosted
        steps:
          - checkout: self
            path: 'wdi23'

          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'wdi23-dzaj(2)(4d28aabf-80b8-4cdd-ae26-9d1032eb12bf)'
              KeyVaultName: 'wdi23kv'
              SecretsFilter: '*'
              RunAsPreJob: false

          - task: CmdLine@2
            inputs:
              script: "sed -i 's/__USER_PAT__/$(WDI-PAT)/g'"

          - task: Docker@2
            displayName: Build docker image
            inputs:
              containerRegistry: wdi23acr
              repository: wdi23-e2e
              command: 'buildAndPush'
              Dockerfile: '$(Agent.BuildDirectory)/wdi23/e2e/Dockerfile'
              tags: 'latest'

          - task: KubernetesManifest@0
            inputs:
              kubernetesServiceConnection: 'wdi23aks'
              action: 'deploy'
              namespace: 'e2e'
              manifests: '$(Agent.BuildDirectory)/wdi23/pipelines/deployment/e2e/deployment.yaml'