trigger: none

stages:
  - stage: Build_Docker_Image
    jobs:
      - job: Docker_Build
        pool: Default
        steps:
          - checkout: self
            path: 'wdi23'

          - task: Docker@2
            displayName: Build docker image
            inputs:
              containerRegistry:
              repository: wdi23-e2e
              command: 'buildAndPush'
              Dockerfile: '/e2e/Dockerfile'