apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e2e-results-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi